<?php /** @var \Tirehub\TirePromo\Block\Promo $block */ ?>

<div
    class="promo-container"
    id="promo-container"
    v-on:click="copyCode"
    v-cloak
>
    <template v-if="promoItems.length">
        <promo-item
            v-for="(promo, index) in promoItems"
            :key="index"
            :index="index"
            :promo="promo"
            v-on:handle-drop-ship-modal="handleDropShipModal"
        ></promo-item>
    </template>
    <div class="message-block info" v-else>{{ t('There are currently no Promo Code available.') }}</div>
    <cancellation-modal
        :show-drop-ship-modal="showDropShipModal"
        :search-url="searchUrl"
        :end-drop-ship-url="endDropShipUrl"
        v-on:on-drop-ship-modal-cancel="onDropShipModalCancel"
        :title="t('Proceeding to Promotion will end dropship. <br> Would you like to continue?')"
    ></cancellation-modal>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Tirehub_TirePromo/js/main": {
                "customer_promo": <?= $block->getCustomerPromoItems(); ?>,
                "endDropShipUrl": "<?= $block->escapeUrl($block->getUrl('dropshipping/ajax/enddropshippingmode')) ?>"
            }
        }
    }
</script>
