<?php /** @var \Tirehub\TirePromo\Block\Promo $block */ ?>

<div
    id="promo-slider-container"
    class="promo-slider-wrapper"
    v-if="promoItems && promoItems.length"
    v-on:click="copyCode"
    v-cloak
>
    <div class="promo-slider-title-wrapper">
        <a class="title" href="<?= $block->escapeUrl($block->getUrl('tirepromo')); ?>">
            <?= $block->escapeHtml(__('Promotions (Click for List)')) ?>
        </a>
    </div>
    <carousel name="promo" :autoplay="true" :slides-length="promoItems.length">
        <div
            class="swiper-slide"
            data-swiper-autoplay="15000"
            v-for="(promo, index) in promoItems"
            :key="index"
        >
            <promo-item
                :promo="promo"
                :index="index"
                promo-ends-message="Ends on "
                v-on:handle-drop-ship-modal="handleDropShipModal"
            ></promo-item>
        </div>
    </carousel>
    <cancellation-modal
        :show-drop-ship-modal="showDropShipModal"
        :search-url="searchUrl"
        :end-drop-ship-url="endDropShipUrl"
        v-on:on-drop-ship-modal-cancel="onDropShipModalCancel"
        :title="t('Proceeding to Promotion will end dropship. <br> Would you like to continue?')"
    ></cancellation-modal>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Tirehub_TirePromo/js/promo-slider" : {
                "customer_promo": <?= $block->getCustomerPromoItems(); ?>,
                "endDropShipUrl": "<?= $block->escapeUrl($block->getUrl('dropshipping/ajax/enddropshippingmode')) ?>"
            }
        }
    }

</script>
