<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Tirehub\Punchout\ViewModel\Punchout $punchoutViewModel */
$punchoutViewModel = $block->getData('punchout_view_model');
$redirectUrl = $punchoutViewModel && $punchoutViewModel->getPunchoutRedirectUrl()
    ? $punchoutViewModel->getPunchoutRedirectUrl()
    : 'customer/account';
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Tirehub_Punchout/js/action/invalidate-and-redirect": {
                "redirectUrl": "<?= $escaper->escapeJs($redirectUrl) ?>"
            }
        }
    }
</script>