<?php
/**
 * @var \Tirehub\TransferNetwork\Block\Map $block
 */
$items = $block->getItems();
$googleMapsApiKey = $this->getGoogleMapsApiKey();
?>

<div id="routes-map-container" class="routes-map-container" v-cloak></div>

<script>
    requirejs(['jquery', 'js/vue-loader', 'Tirehub_TransferNetwork/js/vue/vue-app.min'],
        function($, vueLoader, vueApp) {
            vueLoader({
                componentName: 'RoutesMap',
                props: <?= /* @noEscape */ $items ?>,
                vueApp: vueApp
            }, document.getElementById('routes-map-container'));
        });
</script>

<?php if ($googleMapsApiKey): ?>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<?= $block->escapeHtml($googleMapsApiKey) ?>&language=en&region=US&libraries=places"></script>
<?php endif; ?>

